#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#!/bin/sh

# 禁止提交到某一分支
protected_branch='after' 
remote_branch_prefix="refs/heads/"
protected_remote_branch=$remote_branch_prefix$protected_branch

while read local_ref local_sha remote_ref remote_sha
do
	if [ "$protected_remote_branch" == "$remote_ref" ]; then
		echo ".git/hooks: Do not commit to $protected_branch branch"
	  exit 1
	fi
done

exit 0
